trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Execute Maven Build and Run Unit Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'